# What is numpy?
#### NumPy is a Python package. It stands for ‘Numerical Python’. It is a library consisting of multidimensional
#### array objects and a collection of routines for processing of array.

## How to install NumPy?
#### `pip install numpy`

### The most common way is to import NumPy as the abbreviation `np`
#### `import numpy as np`

In [1]:
import numpy as np

# Data types and attributes
### The main type in NumPy is ndarray(N-dimensional array)

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a1.shape, a1.ndim, a1.size, a1.dtype, type(a1)

((3,), 1, 3, dtype('int32'), numpy.ndarray)

In [4]:
a2 = np.array([[1, 2,3],
              [4, 5.0, 6]])
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a2.shape, a2.size, a2.dtype


((2, 3), 6, dtype('float64'))

In [6]:
a3 = np.array([[[1, 2, 3],
                [4.1, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]]])
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4.1,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]]])

In [7]:
a3.shape, a3.size, a3.dtype

((2, 2, 3), 12, dtype('float64'))

![](./dim.jpeg)

#  Creating arrays
* ### `np.array()`
* ### `np.ones()`
* ### `np.zeros()`
* ### `np.arange()`, `np.linspace()`
* ### `np.random.random()`
    * #### random array of floats between 0 and 1
* ### `np.random.rand()`
* ### `np.random.randint()`
* ### `np.random.randn()`
    * #### return a sample (or samples) from the [standard normal](https://en.wikipedia.org/wiki/Normal_distribution) distribution

In [8]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
zeros.dtype

dtype('float64')

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [13]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [14]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [15]:
np.random.random((2, 3))

array([[0.94926825, 0.86350689, 0.86006071],
       [0.91148323, 0.31997593, 0.01410136]])

In [16]:
np.random.rand(1, 3, 4, 4, 4)

array([[[[[0.8914396 , 0.14355203, 0.23461958, 0.20317987],
          [0.0630907 , 0.83038639, 0.05617593, 0.17293597],
          [0.93433897, 0.05440266, 0.10771737, 0.2057642 ],
          [0.04966019, 0.26680866, 0.26297301, 0.32463147]],

         [[0.81583791, 0.65614518, 0.70751984, 0.1819301 ],
          [0.88738788, 0.24021165, 0.96041286, 0.06302327],
          [0.83819973, 0.12435525, 0.05439966, 0.61186132],
          [0.36953994, 0.82893633, 0.62491159, 0.82186228]],

         [[0.95502411, 0.90221363, 0.65281103, 0.9144089 ],
          [0.29548813, 0.52745777, 0.15250036, 0.36513637],
          [0.69242469, 0.18381973, 0.99365289, 0.2660718 ],
          [0.12990156, 0.0446379 , 0.2323081 , 0.70569453]],

         [[0.29533397, 0.57909958, 0.08411921, 0.83143834],
          [0.66258138, 0.10680855, 0.49997785, 0.82895275],
          [0.58414257, 0.38649417, 0.08851757, 0.64579773],
          [0.62378609, 0.02160453, 0.637608  , 0.83624383]]],


        [[[0.64233102, 0.30929

In [17]:
np.random.randint(10, size=(3, 4))

array([[7, 2, 6, 5],
       [7, 9, 7, 2],
       [9, 3, 1, 8]])

In [18]:
np.random.randn(1, 4)

array([[ 0.14826459, -0.83681442, -1.06025169,  0.75783048]])

# Viewing Matrices and arrays (indexing)

In [86]:
a1, a1.shape, a2, a2.shape, a3, a3.shape

(array([1, 2, 3]),
 (3,),
 array([[1., 2., 3.],
        [4., 5., 6.]]),
 (2, 3),
 array([[[ 1. ,  2. ,  3. ],
         [ 4.1,  5. ,  6. ]],
 
        [[ 7. ,  8. ,  9. ],
         [10. , 11. , 12. ]]]),
 (2, 2, 3))

In [87]:
a1[1]

2

In [88]:
a2[1, 1]

5.0

In [89]:
a3[1, 0, 2]

9.0

In [91]:
a1[:]

array([1, 2, 3])

In [93]:
a2[0]

array([1., 2., 3.])

In [95]:
a3[1]

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [96]:
a1[0:3]

array([1, 2, 3])

In [99]:
a1[1:3]

array([2, 3])

In [101]:
a2[1, :2]

array([4., 5.])

In [102]:
a3[1, :, 1:]

array([[ 8.,  9.],
       [11., 12.]])

# Manipulating and comparing arrays
* ### Arithmetic
    * #### `np.exp()`
    * #### `np.log()`
    * #### `np.dot()`:[Dot product](https://en.wikipedia.org/wiki/Matrix_multiplication)
    * #### `np.multiply()` or `a * b`:[Element-wise product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))
* ### Reshaping
    * #### `np.reshape()`
* ### Transposing
    * #### `A.t` or `np.transpose()`
* ### Aggregation
    * #### `np.sum()`
    * #### `np.mean()`
    * #### `np.min()`
    * #### `np.max()`
    * #### `np.argmin()`
    * #### `np.argmax()`
    * #### 
* ### Comparison operators
    * #### `>`
    * #### `<`
    * #### `>=`
    * #### `<=`
    * #### `a != 2`
    * #### `a == 2`
    * #### `np.sum(a > 2)`

## Arithmetic

In [178]:
a1

array([1, 2, 3])

In [179]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [180]:
np.log(np.exp(a1))

array([1., 2., 3.])

In [181]:
a = np.random.randint(4, size=(300, 20))
b = np.random.randint(4, size=(20, 400))

In [182]:
import time
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print("time: "+str((toc - tic) * 1000 )+ " ms")

time: 3.9987564086914062 ms


In [185]:
ab = np.zeros((a.shape[0], b.shape[1]))
tic = time.time()
for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        for k in range(b.shape[0]):
            ab[i, j] += a[i, k] * b[k, j]
toc = time.time()
print("time: "+str((toc - tic) * 1000 )+ " ms")

time: 3160.5072021484375 ms


In [186]:
a1, a2

(array([1, 2, 3]),
 array([[1., 2., 3.],
        [4., 5., 6.]]))

In [187]:
np.multiply(a1, a2)

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

![](./dot_p.png)

## Reshaping

In [188]:
a1.shape

(3,)

In [194]:
a = np.reshape(a1, (1, 3))

## Transposing

In [195]:
a, a.T

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [196]:
np.transpose(a)

array([[1],
       [2],
       [3]])

## Aggregation

In [198]:
a2, np.sum(a2)

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 21.0)

In [203]:
np.sum(a2, axis=0)

array([5., 7., 9.])

In [201]:
np.mean(a2)

3.5

In [204]:
np.mean(a2, axis=0)

array([2.5, 3.5, 4.5])

In [206]:
np.min(a2)

1.0

In [210]:
np.min(a2, axis = 1)

array([1., 4.])

In [211]:
np.max(a2, axis=0)

array([4., 5., 6.])

In [214]:
np.argmin(a2, axis=0)

array([0, 0, 0], dtype=int64)

In [218]:
np.argmax(a2, axis=1)

array([2, 2], dtype=int64)

In [219]:
np.argmax(a2)

5

## Comparison operators

In [221]:
a1, a2

(array([1, 2, 3]),
 array([[1., 2., 3.],
        [4., 5., 6.]]))

In [222]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [223]:
a1 > 1

array([False,  True,  True])

In [224]:
a1 != 2

array([ True, False,  True])

In [225]:
ab == c

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [226]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [227]:
np.sum(a1 > 2)

1

In [228]:
np.sum(a2 > 2)

4

In [229]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [230]:
np.sum(a2 > a1)

3

In [231]:
a1 = a1 * 2

In [232]:
a1

array([2, 4, 6])

In [233]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [234]:
np.sum(a2 > a1)

2